- name : apache task
  hosts: web
  become: yes

  tasks:
    - name: installing apache using loop
      dnf: 
        name: "{{ item }}"
        state: present
      when: ansible_facts.distribution_major_version=="2023"

      loop:
        - httpd
        - git
        - zip
